export const GIFTS = [
  { id: 1, name: "Wavecat Pillow", grade: "yellow" },
  { id: 2, name: "Peroro Wheel", grade: "yellow" },
  { id: 3, name: "A-Pods Pro", grade: "yellow" },
  { id: 4, name: "Forbidden Love", grade: "yellow" },
  { id: 5, name: "Hitgirls Gaming Magazine", grade: "yellow" },
  { id: 6, name: "Cherry-Rose Lip Gloss", grade: "yellow" },
  { id: 7, name: "Glassy Glow BB Cream", grade: "yellow" },
  { id: 8, name: "Military Camo Foundation Trio", grade: "yellow" },
  { id: 9, name: "Fine Cookie Set", grade: "yellow" },
  { id: 10, name: "Guns, Charm, and Zeal", grade: "yellow" },
  { id: 11, name: "Astronomical Telescope", grade: "yellow" },
  { id: 12, name: "Gamegirl Color Replica", grade: "yellow" },
  { id: 13, name: "MX Ration", grade: "yellow" },
  { id: 14, name: "Matcha Ramune", grade: "yellow" },
  { id: 15, name: "Jellies Cushion", grade: "yellow" },
  { id: 16, name: "Extraordinary Cottontail Detective", grade: "yellow" },
  { id: 17, name: "Ring Fit", grade: "yellow" },
  { id: 18, name: "Buried Treasure Map", grade: "yellow" },
  { id: 19, name: "Cosplayer Coke-Bottle Glasses", grade: "yellow" },
  { id: 20, name: "World's Most Useless Gadget", grade: "yellow" },
  { id: 21, name: "Teddy Bear with Bow", grade: "yellow" },
  { id: 22, name: "Movie Ticket", grade: "yellow" },
  { id: 23, name: "30-Color Paint Set", grade: "yellow" },
  { id: 24, name: "Classical Poetry Anthology", grade: "yellow" },
  { id: 25, name: "Cute Dishware Set", grade: "yellow" },
  { id: 26, name: "Brain Teaser Puzzle Cube", grade: "yellow" },
  { id: 27, name: "Large Whole Cake", grade: "yellow" },
  { id: 28, name: "Luxury Buffet Ticket", grade: "yellow" },
  { id: 29, name: "Potted Bug-Eating Plant", grade: "yellow" },
  { id: 30, name: "Extravagant Gilded Jar of Greed", grade: "yellow" },
  { id: 31, name: "Wind-Up Music Box", grade: "yellow" },
  { id: 32, name: "Embroidered Handkerchief", grade: "yellow" },
  { id: 33, name: "Encyclopedia", grade: "yellow" },
  { id: 34, name: "Health Food Supplement", grade: "yellow" },
  { id: 35, name: "Summer Floaty", grade: "yellow" },
  { id: 36, name: "Lace Pillow", grade: "purple" },
  { id: 37, name: "Streets of Thugs", grade: "purple" },
  { id: 38, name: "Samuela The Beyond", grade: "purple" },
  { id: 39, name: "Antique Egg Handicraft", grade: "purple" },
  { id: 40, name: "Mille-Feuille Traditional Parfait", grade: "purple" },
  { id: 41, name: "Airbook Rare", grade: "purple" },
  { id: 42, name: "Sophisticated Hairbrush", grade: "purple" },
  { id: 43, name: "Nutrient-Packed Multi Vitamin Gummies", grade: "purple" },
  { id: 44, name: "Finest Maple Bonsai", grade: "purple" },
  { id: 45, name: "Sewing Kit", grade: "purple" },
  { id: 46, name: "Music Concert Ticket", grade: "purple" },
  { id: 47, name: "Three Times a Day Dumbbell Set", grade: "purple" },
  { id: 48, name: "Board Game The Life", grade: "purple" },
]