export const GIFTS = [
  { id: 1, name: "Wavecat Pillow" },
  { id: 2, name: "Peroro Wheel" },
  { id: 3, name: "A- Airpods Pro" },
  { id: 4, name: "Forbidden Love" },
  { id: 5, name: "Hitgirls Gaming Magazine" },
  { id: 6, name: "Cherry-Rose Lip Gloss" },
  { id: 7, name: "Glassy Glow BB Cream" },
  { id: 8, name: "Military Camo Foundation Trio" },
  { id: 9, name: "Fine Cookie Set" },
  { id: 10, name: "Guns, Charm, and Zeal" },
  { id: 11, name: "Astronomical Telescope" },
  { id: 12, name: "Gamegirl Color Replica" },
  { id: 13, name: "MX Ration" },
  { id: 14, name: "Matcha Ramune" },
  { id: 15, name: "Jellies Cushion" },
  { id: 16, name: "Extraordinary Cottontail Detective" },
  { id: 17, name: "Ring Fit" },
  { id: 18, name: "Buried Treasure Map" },
  { id: 19, name: "Cosplayer Coke-Bottle Glasses" },
  { id: 20, name: "World's Most Useless Gadget" },
  { id: 21, name: "Teddy Bear with Bow" },
  { id: 22, name: "Movie Ticket" },
  { id: 23, name: "30-Color Paint Set" },
  { id: 24, name: "Classical Poetry Anthology" },
  { id: 25, name: "Cute Dishware Set" },
  { id: 26, name: "Brain Teaser Puzzle Cube" },
  { id: 27, name: "Large Whole Cake" },
  { id: 28, name: "Luxury Buffet Ticket" },
  { id: 29, name: "Potted Bug-Eating Plant" },
  { id: 30, name: "Extravagant Gilded Jar of Greed" },
  { id: 31, name: "Wind-Up Music Box" },
  { id: 32, name: "Embroidered Handkerchief" },
  { id: 33, name: "Encyclopedia" },
  { id: 34, name: "Health Food Supplement" },
  { id: 35, name: "Summer Floaty" },
  { id: 36, name: "Lace Pillow" },
  { id: 37, name: "Streets of Thugs" },
  { id: 38, name: "Samuela The Beyond" },
  { id: 39, name: "Antique Egg Handicraft" },
  { id: 40, name: "Mille-Feuille Traditional Parfait" },
  { id: 41, name: "Airbook Rare" },
  { id: 42, name: "Sophisticated Hairbrush" },
  { id: 43, name: "Nutrient-Packed Multi Vitamin Gummies" },
  { id: 44, name: "Finest Maple Bonsai" },
  { id: 45, name: "Sewing Kit" },
  { id: 46, name: "Music Concert Ticket" },
  { id: 47, name: "Three Times a Day Dumbbell Set" },
  { id: 48, name: "Board Game The Life" },
]